name: creatego
description: CreateGo no-code Package
version: 0.0.1

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # REST API Related Dependencies
  retrofit: ">=3.0.0 <4.0.0"
  dio: ^4.0.1
  json_annotation: ^4.1.0

  # REDUX Related Dependencies
  redux: ^5.0.0
  flutter_redux: ^0.10.0

  # Routing Related Dependencies
  auto_route: ^4.0.1

  # Additional Related Dependencies
  intl: ^0.17.0
  intl_utils: ^2.6.1
  heroicons: ^0.5.0
  dropdown_button2: ^1.7.0
  hovering: ^1.0.4
  flutter_screenutil: ^5.0.0+2
  image_picker: ^0.8.4+11
  mix: ^0.0.6
  flutter_easylogger: ^2.3.3
  flutter_svg: ^1.1.4

  # Database Related Dependencies
  hive: ^2.1.0
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
